#!/bin/bash
#
# The following script downloads the packages defined in composer.json with a single composer update command
# and then point this bins to your /usr/local/bin folder.
# USAGE:
# ./easy
# Follow the instructions

command -v composer >/dev/null 2>&1 || { echo >&2 "I require composer but it's not installed. Aborting."; exit 1; }

LOGFILE=${PWD}/'symlinks.log'
LOCALBIN='/usr/local/bin';
VENDORFOLDER='vendor'
BINFOLDER=$VENDORFOLDER'/bin'

checkPermissions()
{
	if [ ! -w "$LOCALBIN" ] ; then
        printf "You don't have permissions to write to $LOCALBIN \n";
        printf "Please run the script as sudo: sudo ./easy \n";
        exit 1;
    fi
}

firstInstallation()
{
	checkPermissions

	composer install

	PWD=pwd
	cd $BINFOLDER

	BINLIST=`ls`


	for b in $BINLIST; do
		if [ ! -f $LOCALBIN'/'$b ]; then
	    	ln -s $PWD'/'$b $LOCALBIN'/'$b
	    	echo $LOCALBIN'/'$b >> $LOGFILE;
	    fi
	done

	printf "That's it! These tools are now available on your system:\n${BINLIST[@]}\n\n"
	printf "Now just use it!\n";

	exit 1;
}

update()
{
	composer update

	printf "Packages are successfully updated\n";

	exit 1;
}

uninstall()
{
	checkPermissions
	
	if [ ! -f $LOGFILE ]; then echo "No packages to remove" exit 1; fi

	while read binlink; do
		if [ -f "$binlink" ]; then
			rm $binlink;
		fi
	done < $LOGFILE

	if [ -d $VENDORFOLDER ]; then
		rm -rf $VENDORFOLDER
	fi

	if [ -f "composer.lock" ]; then
		rm "composer.lock"
	fi

	if [ -f "$LOGFILE" ]; then
		rm "$LOGFILE"
	fi

	printf "\nSuccessfully uninstalled\nThanks!\n";

	exit 1;
}


printf "Easy install PHP QA Tools:\n";
select iur in "First installation" "Update packages" "Uninstall" "Quit"; do
    case $iur in
        "First installation" ) firstInstallation; break;;
		"Update packages" ) update; break;;
		"Uninstall" ) uninstall; break;;
        "Quit" ) exit 1;
    esac
done